### ISSUE TITLE
Make compatible with other IDEs

### ISSUE THREAD

**Issue by lancelote** [AlexeyKozyakov/inspection-compare#14]
I tried the plugin with PyCharm (by changing `plugin.xml`) and it seems to work correctly, can it be marked compatible with other IDEs or are there any pitfalls?

**Comment by AlexeyKozyakov** [comment]
A new version of plugin now is available. It is compatible with IntelliJ IDEA,  PhpStorm , WebStorm,  PyCharm,  RubyMine,  AppCode,  CLion,  GoLand,  Rider.

**Comment by AlexeyKozyakov** [comment]
> I tried the plugin with PyCharm (by changing `plugin.xml`) and it seems to work correctly, can it be marked compatible with other IDEs or are there any pitfalls?

A new version of plugin now is available. It is compatible with IntelliJ IDEA, PhpStorm , WebStorm, PyCharm, RubyMine, AppCode, CLion, GoLand, Rider.

**Comment by lancelote** [comment]
Thank you.
